### ISSUE TITLE
parameters_simulate -> simulate_parameters?

### ISSUE THREAD

**Issue by strengejacke** [easystats/parameters#168]
@DominiqueMakowski we have a naming convention that says we should use common prefixes, like we have for `performance_*()` or `check_*()`. We do the same for `parameters_simulate()` and `model_simulate()`, however, it feels more natural to me to name these functions `simulate_parameters()` and `simulate_model()`, like the simulate functions in bayestestR.

What do you think?

**Comment by strengejacke** [comment]
Well, actually our style guide says that the common prefix should indicate the common _task_ functions deal with. So renaming would be even in line with our style rules.

We could even further think about:
- `reduce_parameters()`
- `select_parameters()`
- `bootstrap_model()/_parameters()`

**Comment by DominiqueMakowski** [comment]
mmh but then isn't nice to have all these parameters_* functions? I mean why not, but for instance for `reduce_parameters` it will lose its "cluster" belonging as there isn't any other function for now with `reduce_`. 

I am facing the same issue in the new [neurokit](https://github.com/neuropsychology/NeuroKit) python package that I am re-writing. In the first version, I had a function named `find_events`, and other functions starting with `find_*`. Although `find_events` does sound more natural (and I love natural-language looking code), I decided to rename it `events_find` because here the most important aspect of the function is that it's specific to events (and should figure alongside other events-related functions, rather than with all the `find_` stuff which is very diverse).

So I think it's more about conceptual grouping than hard rules to follow. But in this case, I won't argue against renaming it as I don't have a strong opinion on it

**Comment by strengejacke** [comment]
I have just looked at the [list of functions](https://github.com/easystats/easystats#list-of-functions). Whenever we have a common prefix, it is either a _verb_ (like `describe_*()` or `standardize_*()`), when it's a common index (`r2_*()`) or when in cases like `performance_*()` or `item_*()`. But we actually have never a common prefix and the _verb_ that describes the _task_ as second part, like in `parameters_selection()` or `parameters_simulate()`.

Thus, I would at least add aliases, and maybe deprecate the other function names later. It would fit better into the complete set of functions we have across our packages, I think.

**Comment by DominiqueMakowski** [comment]
Okee, that seems fair. Maybe let's start with aliasing, we can deprecate later.

**Comment by strengejacke** [comment]
Do you know how `@aliases` works in roxygen?

**Comment by DominiqueMakowski** [comment]
nope, never used that

**Comment by strengejacke** [comment]
Ok, I think you can add keywords for `?alias1` or `?alias2`, but it does not add alias _names_ to the namespace.
