### ISSUE TITLE
Support for rms-package

### ISSUE THREAD

**Issue by mattansb** [easystats/parameters#246]
``` r
library(rms)

fit <- ols(Sepal.Width ~ Petal.Width + Petal.Length, data = iris)
aov_table <- anova(fit)

parameters::model_parameters(fit)
#> Error in gsub("Statistic", gsub("-statistic", "", attr(statistic, "statistic", : invalid 'replacement' argument
parameters::model_parameters(aov_table)
#> Parameters can't be retrieved for objects of class 'simpleError'.
#> Error: $ operator is invalid for atomic vectors
```

<sup>Created on 2020-04-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

(required for https://github.com/easystats/effectsize/issues/67)

**Comment by strengejacke** [comment]
Damn. Thought I could pass this work down to you ;-)

**Comment by strengejacke** [comment]
Related to https://github.com/easystats/insight/issues/179

**Comment by strengejacke** [comment]
Working with:

- [x] lrm

**Comment by IndrajeetPatil** [comment]
It will be also nice for `parameters` to support this when it becomes available in CRAN version:
http://hbiostat.org/R/rms/blrm.html

**Comment by strengejacke** [comment]
> It will be also nice for `parameters` to support this when it becomes available in CRAN version:
> http://hbiostat.org/R/rms/blrm.html

I would say this is something to address in insight and bayestestR...

**Comment by strengejacke** [comment]
``` r
library(rms)
fit <- ols(Sepal.Width ~ Petal.Width + Petal.Length, data = iris)
aov_table <- anova(fit)

parameters::model_parameters(fit)
#> Parameter    | Coefficient |   SE |         95% CI |     t |  df |      p
#> -------------------------------------------------------------------------
#> Intercept    |        3.59 | 0.09 | [ 3.40,  3.77] | 38.27 | 147 | < .001
#> Petal.Width  |        0.36 | 0.15 | [ 0.06,  0.67] |  2.35 | 147 | 0.020 
#> Petal.Length |       -0.26 | 0.07 | [-0.39, -0.13] | -3.84 | 147 | < .001
parameters::model_parameters(aov_table)
#> df  | Mean_Square |     F |      p
#> ----------------------------------
#> 1   |        0.84 |  5.52 | 0.020 
#> 1   |        2.24 | 14.77 | < .001
#> 2   |        3.02 | 19.90 | < .001
#> 147 |        0.15 |       |
```

<sup>Created on 2020-06-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Ok, @mattansb , now it's your turn to add support in _effectsize_...

**Comment by mattansb** [comment]
@strengejacke Just realized that `anova.rms` does not return the SS but the partial SS :/

**Comment by strengejacke** [comment]
> Also, not sure what this means for effect size calculations...

hm, I have no idea...

**Comment by strengejacke** [comment]
> It will be also nice for `parameters` to support this when it becomes available in CRAN version:
> http://hbiostat.org/R/rms/blrm.html

@IndrajeetPatil you could open an issue in _insight_, and maybe provide a working example?

**Comment by mattansb** [comment]
@strengejacke Also.... the df column name is `df_residual` but it is a mix of numerator and denominator df, so maybe just `df`?

**Comment by strengejacke** [comment]
Yeah, that should be fixed already. My example was from a previous commit.

**Comment by diegoreinero** [comment]
Hi @strengejacke (and hey @IndrajeetPatil!)

Thanks for all your work on sjplot! I'm new to sjplot so apologies if this is a basic question, but I was following the examples [here](https://cran.r-project.org/web/packages/sjPlot/vignettes/plot_model_estimates.html) and ran a mixed model with `lmer`, but when I tried to get a forest plot of the estimates using `plot_model(fit)` I got this error message: 

`Error in gsub("Statistic", gsub("-statistic", "", attr(statistic, "statistic",  : invalid 'replacement' argument`.

I was confused, so I played around with some basic toy models to see if I could home in on the issue...
> df <- data.frame(
       y = to_factor(y),
        sex = to_factor(efc$c161sex),
        dep = to_factor(efc$e42dep),
        barthel = efc$barthtot,
        education = to_factor(efc$c172code)
)
m <- lm(barthel ~ sex*dep, data = df)
plot_model(m)

This plot produces the expected forest plot of the estimates with their standard errors. However, if I now run a mixed model simply adding a random effect...
> m <- lmer(barthel ~ sex*dep + (1 | education), data = df)
plot_model(m)

That no longer works and it produces the error message I described above. Since the error message is the same, I assume the error here is the same one I'm having with my actual data/model. Do you have any suggestions? Is `plot_model` able to create a forest plot of the estimates from mixed models via `lmer`? Apologies if I'm missing something obvious (I know it says [here](https://cran.r-project.org/web/packages/sjPlot/vignettes/plot_model_estimates.html) that `plot_model` accepts many model-objects like `lm`, `glm`, `lme`, `lmerMod` etc so I assume I'm just missing something)!

Best,
Diego
