### ISSUE TITLE
Get standard errors from models

### ISSUE THREAD

**Issue by strengejacke** [easystats/parameters#29]
In many cases, we get this from the `summary()`, but not all. `insight::get_parameters()` might help to find this out for different models.

But we should include a function like `se()` or maybe `std_error()` or whatever, because we then have all we need for:

- coefficients
- se
- p-value
- ci

and thus we have a light-weight broom-alternative.

**Comment by DominiqueMakowski** [comment]
I agree

Although I think that even currently for the classes for which `model_parameters()` is implemented, it returns the SEs. But yes, having a separate function that returns only SEs could be useful.

I think `se` works, since it's coherent with `ci` and since this index's abbreviation as `SE` is rather accepted?

**Comment by strengejacke** [comment]
> I think se works, since it's coherent with ci and since this index's abbreviation as SE is rather accepted?

Yes, I would say so, too.
