### ISSUE TITLE
knit_print methods and/or table helpers

### ISSUE THREAD

**Issue by bwiernik** [easystats/parameters#470]
The print output for parameters tables and other tables is very nearly valid markdown syntax. What is missing is (1) opening and closing vertical bars on each line and (2) alignment indicators for the columns. We could pretty easily add `knit_print` methods that would actually generate valid markdown tables 

This could involve:
1. Adding a `knit_print` argument to all of the `print()` methods that is passed to `.print_core()`.
2. In `.print_core()`, when `knit_print` is TRUE, adding the missing vertical bars and alignment indicators.
3. Adding `knit_print()` methods for each model that calls `print()` with `knit_print = TRUE` and returns `asis_output`. 

Two other options:
1. Just make the tables always valid markdown. They look nearly the same:

```
|Parameter   | Coefficient|   SE|         95% CI| t(358)|      p|
|:-----------|-----------:|----:|--------------:|------:|------:|
|(Intercept) |       65.80| 0.38| [65.05, 66.55]| 172.25| < .001|
|year_1952   |        0.22| 0.01| [ 0.20,  0.25]|  18.86| < .001|
```

```
Parameter   | Coefficient |   SE |         95% CI | t(358) |      p
-------------------------------------------------------------------
(Intercept) |       65.80 | 0.38 | [65.05, 66.55] | 172.25 | < .001
year_1952   |        0.22 | 0.01 | [ 0.20,  0.25] |  18.86 | < .001
```

2. Separate the formatting/captioning/titling steps and the actual printing into two parts, then export the formatting function. This would have the additional advantage that users could then format the parameter tables as they see fit with other packages. This might be a good idea even if 1. is also done.

Thoughts?

**Comment by strengejacke** [comment]
Currently, we have:

- `print()` -> text / console
- `print_html()` -> html
- `print_md()` -> knitr / markdown

I tried something with knit_print / asis, but that somehow didn't work, so we decided to have dedicated print-methods for the different output formats.

Or you have `display(..., format = "<text/markdown/html>")`.

We started working on vignettes:
https://easystats.github.io/insight/articles/display.html
https://easystats.github.io/parameters/articles/model_parameters_formatting.html

**Comment by bwiernik** [comment]
Got it, that's really helpful. `format_table()` was the function I was missing. 

(Sorry for all of these questions--really big set of functions that's taking me a minute to wrap my head around.)

**Comment by strengejacke** [comment]
Yes, even I regularly lose track of all the numerous functions in the easystats eco-system ;-)
And the print-options are indeed rather new...

**Comment by DominiqueMakowski** [comment]
> Yes, even I regularly lose track of all the numerous functions in the easystats eco-system ;-)

Absolutely ^^ 

> And the print-options are indeed rather new...

Because I couldn't remember how it worked, we started [a vignette](https://github.com/easystats/insight/blob/master/vignettes/display.Rmd) to present and summarize the easystats plotting, but the vignette needs more love

**Comment by IndrajeetPatil** [comment]
> Yes, even I regularly lose track of all the numerous functions in the easystats eco-system ;-)

I think we are at a stage where we can start making cheatsheets for `easystats` packages 😅

**Comment by strengejacke** [comment]
Tagging @vincentarelbundock here. While the easystats packages provide some basic printing options for HTML / markdown, the integration of _parameters_ and _performance_ into the _modelsummary_ package allows to create very flexible and complex tables. We may add a vignette that demonstrate the usage of _modelsummary_ specifically for the purpose of the easystats-ecosystem, i.e. easily deal with regression models in R, and how to get readable outputs.

The existence of _modelsummary_ somehow also makes the _sjPlot_ package obsolete, that's also a reason why I put more resources into _easystats_ and _ggeffects_, rather than _sjPlot_ or _sjstats_.

**Comment by vincentarelbundock** [comment]
Thanks for the plug @strengejacke ! I'd be very happy to contribute to such a vignette if you think my input would be useful. Also, everyone should feel free to point me to missing features in `modelsummary`. I'm eager to reach feature parity with the main alternatives.

On the topic of this thread, I think it's quite important to *not* define new print methods for object classes that were defined and created by other packages. Otherwise, a mere call to `library()` can change the output of a script, which IMHO is bad in terms of reproducibility. It's also quite puzzling for users, as shown here: https://github.com/vincentarelbundock/modelsummary/issues/256

**Comment by strengejacke** [comment]
> On the topic of this thread, I think it's quite important to _not_ define new print methods for object classes that were defined and created by other packages. Otherwise, a mere call to `library()` can change the output of a script, which IMHO is bad in terms of reproducibility. It's also quite puzzling for users, as shown here: [vincentarelbundock/modelsummary#256](https://github.com/vincentarelbundock/modelsummary/issues/256)

Not sure if we're talking about the same issue here, but you can define `knit_print()` for own classes, so no problems with changing behaviour should happen. See e.g. https://github.com/strengejacke/sjPlot/blob/master/R/S3-methods.R

**Comment by vincentarelbundock** [comment]
Wow, I totally missed the boat on that one (advice: never comment on github issues within 20 minutes of waking up!).

Of course that's fine.
