### ISSUE TITLE
Error in model_parameters with robust = TRUE

### ISSUE THREAD

**Issue by marcozanotti** [easystats/parameters#580]
Error: Sorry, `model_parameters()` does currently not work for objects of class 'lm'.

Using **model_parameters** with argument **robust = TRUE** does not work if the package **sandwich** is not installed.
No dependency on sandwich is specified.

**Comment by marcozanotti** [comment]
@mattansb, in my opinion, if a function relies strictly on functions of other packages to work, those packages should be listed in Dependency, not in Suggests.

**Comment by IndrajeetPatil** [comment]
In `easystats` ecosystem, we have a 0 external dependency policy. So, no, we will not be adding it to `Imports`, but will have it only in `Suggests`.

It doesn't make sense to gain a dependency, which might be used only in certain contexts. Otherwise, we will end up importing all these packages:

![image](https://user-images.githubusercontent.com/11330453/129009881-7ca5d3f5-f170-4059-8b2e-d0b1c9af968e.png)

**Comment by DominiqueMakowski** [comment]
That said, didn't we have a function in `easystats` to install all the suggests at once? or was it just a "feature idea" ?

**Comment by IndrajeetPatil** [comment]
Yes, this one:
https://easystats.github.io/easystats/reference/install_suggested.html

**Comment by marcozanotti** [comment]
@mattansb @IndrajeetPatil  thanks for your clarifications.

**Comment by strengejacke** [comment]
> Shouldn't this be error be:

The problem is here that we `tryCatch()` the complete stuff, including calling robust methods, so any failure/error/stop will return `NULL` - no matter, whether it's a missing pkg that `stop()`s the function, or any other issue.

https://github.com/easystats/parameters/blob/9325f005e425014d6ed6fdd942eb535ed652a0b0/R/1_model_parameters.R#L283-L305

**Comment by mattansb** [comment]
Currently:

1. Try to run code
2. If fails, return NULL
3. if NULL, stop with custom error

Why not just skip (2) and let the function error with it's original error?

**Comment by mattansb** [comment]
Maybe:

```R
out <- tryCatch(
  {
    .model_parameters_generic(
      model = model,
      ci = ci,
      bootstrap = bootstrap,
      iterations = iterations,
      merge_by = "Parameter",
      standardize = standardize,
      exponentiate = exponentiate,
      robust = robust,
      p_adjust = p_adjust,
      summary = summary,
      keep_parameters = keep,
      drop_parameters = drop,
      verbose = verbose,
      ...
    )
  },
  error = function(e) {
    out <- NA
    attr(out, "error") <- e$message
    out
  }
)

if (is.na(out)) {
  stop("Sorry, `model_parameters()` failed with the following error (possible class '", class(model)[1], "' not supported):\n",
       attr(out, "error"),
       call. = FALSE)
}
```

**Comment by strengejacke** [comment]
I can try that. I already tried something similar, like `out <- e$message`, but then `stop(out)` just returned a character vector (with the message), and did not `stop()` - no idea, why...
