### ISSUE TITLE
Model_parameters with standardize = 'refit' - suddenly stopped working without any error

### ISSUE THREAD

**Issue by marta7kowal** [easystats/parameters#731]
Hello,
I have been running some stats on the same dataset with the same code and everything worked perfectly. However, today I updated R (now 4.2..0) and RStudio (2022.02.3+492), installed all the packages and suddenly, model_parameters with standardize = 'refit' stopped working. No error, no anything - it keeps converging ad infinitum. Weirdly, when I try to do standardize = 'basic', it works. On another laptop, I tried redoing everything, and it only works if I first try to run model_parameters with standardize = 'basic', and then switch back to 'refit'.

I am completely clueless about what the issue might be... Do you perhaps, have any idea? Thanks in advance!
Kind regards

**Comment by marta7kowal** [comment]
Fix that worked for me: I uninstalled merDeriv package and it started working again. Maybe it might be of help for anyone else encountering such an issue.

**Comment by strengejacke** [comment]
We improved the calculation of standard errors and confidence intervals for the random effects parameters from mixed models. I guess, this is the issue you ran into. However, instead of uninstalling the _merDeriv_ package, you can also set `effects = "fixed"` and random effects parameters and their CIs are not included.

Do you have a reproducible example, so we might check if we can solve this problem from our side?

**Comment by strengejacke** [comment]
Short update: you can also use `ci_random = FALSE` to explicitly suppress calculation of confidence intervals for random effects.
